### ISSUE TITLE
/api/update_status/offline/

### ISSUE THREAD

**Issue by wayzeek** [Tonisos/transcendence#77]
###  Erreurs : 
- NS_BINDING_ABORT
- Error updating status: TypeError: NetworkError when attempting to fetch resource. utils.js:101:17
    setStatus https://localhost:8080/js/utils.js:101
 
 ### Cas d'erreur :
 1. Log-in with 42
 2. Logout
 3. Log-in with 42 (again)

**Comment by MaddRaven** [comment]
Je n'ai pas l'erreur de mon cote
